# Generated by Django 6.1 on 2026-09-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_crop_order_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='farmer_name',
            field=models.CharField(default='Farmer', max_length=100),
        ),
    ]
